apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-app
spec:
  destination:
    namespace: demo-bgdk
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/bgdk
    repoURL: https://github.com/bizcochillo/openshift-gitops-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
