apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
spec:
  destination:
    namespace: demo-todo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/todo
    repoURL: https://github.com/bizcochillo/openshift-gitops-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
